name: BetterNetherite
version: '${project.version}'
api-version: '1.16'
main: com.github.steeldev.betternetherite.BetterNetherite
description: A plugin that brings a few changes to 1.16s new Netherite.
author: Steel_Dev
commands:
  betternetheritereload:
    description: Reload the configuration.
    aliases: bnreload
    permission: betternetherite.admin
    permission-message: You dont have permission to use this command.
permissions:
  betternetherite.admin:
    description: Allows the user administrator permissions for Better Netherite.
    default: op
